Ext.define('Bloodbank.bloodbank.shared.com.model.bloodbank.BloodRequestModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bloodRequestId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "noOfUnits",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "patientName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "requestedByDoctor",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "requestedByHospital",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dateNeededBy",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "dispatchedToPatientOnDT",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "bloodgroup",
          "reference": "BloodGroup",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});