Ext.define('Bloodbank.bloodbank.shared.com.model.bloodbank.RegisterACampModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "registerACampId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "organisationName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "reasonForCamp",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bloodBankName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "fromDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "toDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "noOfDonorsExpected",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "noOfDonorsThatArrived",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "noOfDonorsThatBled",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "campTime",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "Address",
          "reference": "AddressModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});