Ext.define('Bloodbank.bloodbank.shared.com.model.bloodbank.RegisterADonorModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "registerADonorId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "donorName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dateOfBirth",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "phoneNo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "emailId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "lastDonationDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "howoftenyoudonatedinpast",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "gender",
          "reference": "Gender",
          "defaultValue": ""
     }, {
          "name": "bloodgroup",
          "reference": "BloodGroup",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "Address",
          "reference": "AddressModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});